biydaalt/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using biydaalt.Models;

namespace biydaalt.Controllers
{
    public class BookController : Controller
    {
        private readonly Nomiinsanctx _context;

        public BookController(Nomiinsanctx context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var nomiinsanctx = _context.books.Include(b => b.dedturuluud).Include(b => b.turuluud).Include(b => b.worker);
            return View(await nomiinsanctx.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.books
                .Include(b => b.dedturuluud)
                .Include(b => b.turuluud)
                .Include(b => b.worker)
                .FirstOrDefaultAsync(m => m.bookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["dedTurulId"] = new SelectList(_context.dedTuruls, "dedTurulId", "dedTurulName");
            ViewData["turulId"] = new SelectList(_context.turuls, "turulId", "turulName");
            ViewData["workerId"] = new SelectList(_context.workers, "workerId", "workerName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("bookId,bookName,bookimage,author,page_count,turulId,dedTurulId,book_count,pub_date,pub_company,price,workerId")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["dedTurulId"] = new SelectList(_context.dedTuruls, "dedTurulId", "dedTurulName", book.dedTurulId);
            ViewData["turulId"] = new SelectList(_context.turuls, "turulId", "turulName", book.turulId);
            ViewData["workerId"] = new SelectList(_context.workers, "workerId", "workerName", book.workerId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["dedTurulId"] = new SelectList(_context.dedTuruls, "dedTurulId", "dedTurulName", book.dedTurulId);
            ViewData["turulId"] = new SelectList(_context.turuls, "turulId", "turulName", book.turulId);
            ViewData["workerId"] = new SelectList(_context.workers, "workerId", "workerName", book.workerId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("bookId,bookName,bookimage,author,page_count,turulId,dedTurulId,book_count,pub_date,pub_company,price,workerId")] Book book)
        {
            if (id != book.bookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.bookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["dedTurulId"] = new SelectList(_context.dedTuruls, "dedTurulId", "dedTurulName", book.dedTurulId);
            ViewData["turulId"] = new SelectList(_context.turuls, "turulId", "turulName", book.turulId);
            ViewData["workerId"] = new SelectList(_context.workers, "workerId", "workerName", book.workerId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.books
                .Include(b => b.dedturuluud)
                .Include(b => b.turuluud)
                .Include(b => b.worker)
                .FirstOrDefaultAsync(m => m.bookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.books.FindAsync(id);
            if (book != null)
            {
                _context.books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.books.Any(e => e.bookId == id);
        }
    }
}

biydaalt/Controllers/Home1Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace biydaalt.Controllers
{
    public class Home1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

biydaalt/Controllers/TurulController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using biydaalt.Models;

namespace biydaalt.Controllers
{
    public class TurulController : Controller
    {
        private readonly Nomiinsanctx _context;

        public TurulController(Nomiinsanctx context)
        {
            _context = context;
        }

        // GET: Turul
        public async Task<IActionResult> Index()
        {
            return View(await _context.turuls.ToListAsync());
        }
        public async Task<IActionResult> Indexu()
        {
            return View(await _context.turuls.ToListAsync());
        }

        // GET: Turul/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turul = await _context.turuls
                .FirstOrDefaultAsync(m => m.turulId == id);
            if (turul == null)
            {
                return NotFound();
            }

            return View(turul);
        }

        // GET: Turul/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Turul/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("turulId,turulName")] Turul turul)
        {
            if (ModelState.IsValid)
            {
                _context.Add(turul);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(turul);
        }

        // GET: Turul/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turul = await _context.turuls.FindAsync(id);
            if (turul == null)
            {
                return NotFound();
            }
            return View(turul);
        }

        // POST: Turul/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("turulId,turulName")] Turul turul)
        {
            if (id != turul.turulId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(turul);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TurulExists(turul.turulId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(turul);
        }

        // GET: Turul/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turul = await _context.turuls
                .FirstOrDefaultAsync(m => m.turulId == id);
            if (turul == null)
            {
                return NotFound();
            }

            return View(turul);
        }

        // POST: Turul/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var turul = await _context.turuls.FindAsync(id);
            if (turul != null)
            {
                _context.turuls.Remove(turul);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TurulExists(int id)
        {
            return _context.turuls.Any(e => e.turulId == id);
        }
    }
}

biydaalt/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using biydaalt.Models;

namespace biydaalt.Controllers
{
    public class WorkerController : Controller
    {
        private readonly Nomiinsanctx _context;

        public WorkerController(Nomiinsanctx context)
        {
            _context = context;
        }

        // GET: Worker
        public async Task<IActionResult> Index()
        {
            var nomiinsanctx = _context.workers.Include(w => w.albantushaal).Include(w => w.department);
            return View(await nomiinsanctx.ToListAsync());
        }

        // GET: Worker/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.workers
                .Include(w => w.albantushaal)
                .Include(w => w.department)
                .FirstOrDefaultAsync(m => m.workerId == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // GET: Worker/Create
        public IActionResult Create()
        {
            ViewData["albantushaalId"] = new SelectList(_context.albantushaals, "albantushaalId", "albantushaalName");
            ViewData["departmentId"] = new SelectList(_context.departments, "departmentId", "departmentName");
            return View();
        }

        // POST: Worker/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("workerId,workerName,departmentId,albantushaalId,regdug,phone")] Worker worker)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(worker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["albantushaalId"] = new SelectList(_context.albantushaals, "albantushaalId", "albantushaalId", worker.albantushaalId);
            ViewData["departmentId"] = new SelectList(_context.departments, "departmentId", "departmentName", worker.departmentId);
            return View(worker);
        }

        // GET: Worker/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.workers.FindAsync(id);
            if (worker == null)
            {
                return NotFound();
            }
            ViewData["albantushaalId"] = new SelectList(_context.albantushaals, "albantushaalId", "albantushaalName", worker.albantushaalId);
            ViewData["departmentId"] = new SelectList(_context.departments, "departmentId", "departmentName", worker.departmentId);
            return View(worker);
        }

        // POST: Worker/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("workerId,workerName,departmentId,albantushaalId,regdug,phone")] Worker worker)
        {
            if (id != worker.workerId)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(worker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkerExists(worker.workerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["albantushaalId"] = new SelectList(_context.albantushaals, "albantushaalId", "albantushaalName", worker.albantushaalId);
            ViewData["departmentId"] = new SelectList(_context.departments, "departmentId", "departmentName", worker.departmentId);
            return View(worker);
        }

        // GET: Worker/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.workers
                .Include(w => w.albantushaal)
                .Include(w => w.department)
                .FirstOrDefaultAsync(m => m.workerId == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // POST: Worker/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var worker = await _context.workers.FindAsync(id);
            if (worker != null)
            {
                _context.workers.Remove(worker);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkerExists(int id)
        {
            return _context.workers.Any(e => e.workerId == id);
        }
    }
}

biydaalt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - biydaalt</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/biydaalt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home1" asp-action="Index">biydaalt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home1" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turul" asp-action="Indexu">Төрөл</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Мандах Их Сургууль - 
            <a href="#"><i class="fa-brands fa-facebook"></i></a>
            <a href="#"><i class="fa-brands fa-twitter"></i></a>
            <a href="#"><i class="fa-brands fa-youtube"></i></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

biydaalt/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - biydaalt</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/biydaalt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">biydaalt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Admin Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Admin Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="dataDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" asp-area="" asp-controller="Dedturul" asp-action="Index">
                                Лавлах
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dataDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Dedturul" asp-action="Index">
                                        Дэд төрөл
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Turul" asp-action="Index">Төрөл</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Albantushaal" asp-action="Index">Албан тушаал</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="Index">Хэлтэс</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Actshaltgaan" asp-action="Index">Актласан шалтгаан</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Torguulishaltgaan" asp-action="Index">Торгуулийн шалтгаан</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="dataDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" asp-area="" asp-controller="Dedturul" asp-action="Index">
                                Бүртгэл
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dataDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bookact" asp-action="Index">Ном актлалт</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bookgive" asp-action="Index">Ном олголт</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Ном</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Worker" asp-action="Index">Ажилтан</a>
                                </li>
                            </ul>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Мандах Их Сургууль - 
            <a href="#"><i class="fa-brands fa-facebook"></i></a>
            <a href="#"><i class="fa-brands fa-twitter"></i></a>
            <a href="#"><i class="fa-brands fa-youtube"></i></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>